### ISSUE TITLE
Wrong header names

### ISSUE THREAD

**Issue by sggottlieb** [workaandrey/ondemand-php-sdk#1]
Hi Andrey,

Please update ApiClient.generateAuthHeaders to use the proper header names:

x-lod-timestamp
x-lod-version

Notice the dashes instead of underscores.

The onDemand API used to accept underscores even though they were wrong but a recent Apache upgrade forbids the use or underscores in header names for security reasons.  

Thanks,

Seth

**Comment by workaandrey** [comment]
Fixed
